import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'bn';

interface Translations {
  [key: string]: {
    en: string;
    bn: string;
  };
}

export const translations: Translations = {
  // Navigation
  'nav.dashboard': { en: 'Dashboard', bn: 'ড্যাশবোর্ড' },
  'nav.products': { en: 'Products', bn: 'প্রোডাক্ট' },
  'nav.orders': { en: 'Orders', bn: 'অর্ডার' },
  'nav.customers': { en: 'Customers', bn: 'কাস্টমার' },
  'nav.categories': { en: 'Categories', bn: 'ক্যাটাগরি' },
  'nav.shipping': { en: 'Shipping', bn: 'শিপিং' },
  'nav.analytics': { en: 'Analytics', bn: 'অ্যানালিটিক্স' },
  'nav.messages': { en: 'Messages', bn: 'মেসেজ' },
  'nav.reports': { en: 'Reports', bn: 'রিপোর্ট' },
  
  'nav.coupons': { en: 'Coupons', bn: 'কুপন' },
  'nav.settings': { en: 'Settings', bn: 'সেটিংস' },
  'nav.logout': { en: 'Logout', bn: 'লগআউট' },
  'nav.menu': { en: 'Menu', bn: 'মেনু' },
  'nav.management': { en: 'Management', bn: 'ম্যানেজমেন্ট' },
  'nav.profile': { en: 'Profile', bn: 'প্রোফাইল' },
  'nav.roles': { en: 'Role Management', bn: 'রোল ম্যানেজমেন্ট' },

  // Common
  'common.search': { en: 'Search', bn: 'খুঁজুন' },
  'common.add': { en: 'Add', bn: 'যোগ করুন' },
  'common.edit': { en: 'Edit', bn: 'এডিট' },
  'common.delete': { en: 'Delete', bn: 'মুছুন' },
  'common.save': { en: 'Save', bn: 'সেভ করুন' },
  'common.cancel': { en: 'Cancel', bn: 'বাতিল' },
  'common.confirm': { en: 'Confirm', bn: 'নিশ্চিত' },
  'common.status': { en: 'Status', bn: 'স্ট্যাটাস' },
  'common.actions': { en: 'Actions', bn: 'অ্যাকশন' },
  'common.all': { en: 'All', bn: 'সব' },
  'common.active': { en: 'Active', bn: 'সক্রিয়' },
  'common.inactive': { en: 'Inactive', bn: 'নিষ্ক্রিয়' },
  'common.filter': { en: 'Filter', bn: 'ফিল্টার' },
  'common.export': { en: 'Export', bn: 'এক্সপোর্ট' },
  'common.import': { en: 'Import', bn: 'ইমপোর্ট' },
  'common.download': { en: 'Download', bn: 'ডাউনলোড' },
  'common.total': { en: 'Total', bn: 'মোট' },
  'common.view': { en: 'View', bn: 'দেখুন' },
  'common.details': { en: 'Details', bn: 'বিস্তারিত' },
  'common.name': { en: 'Name', bn: 'নাম' },
  'common.email': { en: 'Email', bn: 'ইমেইল' },
  'common.phone': { en: 'Phone', bn: 'ফোন' },
  'common.address': { en: 'Address', bn: 'ঠিকানা' },
  'common.date': { en: 'Date', bn: 'তারিখ' },
  'common.amount': { en: 'Amount', bn: 'পরিমাণ' },
  'common.price': { en: 'Price', bn: 'মূল্য' },
  'common.quantity': { en: 'Quantity', bn: 'পরিমাণ' },

  // Dashboard
  'dashboard.title': { en: 'Dashboard', bn: 'ড্যাশবোর্ড' },
  'dashboard.welcome': { en: 'Welcome back', bn: 'স্বাগতম' },
  'dashboard.totalSales': { en: 'Total Sales', bn: 'মোট বিক্রয়' },
  'dashboard.totalOrders': { en: 'Total Orders', bn: 'মোট অর্ডার' },
  'dashboard.totalCustomers': { en: 'Total Customers', bn: 'মোট কাস্টমার' },
  'dashboard.totalProducts': { en: 'Total Products', bn: 'মোট প্রোডাক্ট' },
  'dashboard.recentOrders': { en: 'Recent Orders', bn: 'সাম্প্রতিক অর্ডার' },
  'dashboard.topProducts': { en: 'Top Products', bn: 'টপ প্রোডাক্ট' },

  // Products
  'products.title': { en: 'Products', bn: 'প্রোডাক্ট' },
  'products.addProduct': { en: 'Add Product', bn: 'প্রোডাক্ট যোগ করুন' },
  'products.editProduct': { en: 'Edit Product', bn: 'প্রোডাক্ট এডিট করুন' },
  'products.productName': { en: 'Product Name', bn: 'প্রোডাক্ট নাম' },
  'products.category': { en: 'Category', bn: 'ক্যাটাগরি' },
  'products.stock': { en: 'Stock', bn: 'স্টক' },
  'products.inStock': { en: 'In Stock', bn: 'স্টকে আছে' },
  'products.outOfStock': { en: 'Out of Stock', bn: 'স্টক শেষ' },
  'products.lowStock': { en: 'Low Stock', bn: 'কম স্টক' },

  // Orders
  'orders.title': { en: 'Orders', bn: 'অর্ডার' },
  'orders.orderId': { en: 'Order ID', bn: 'অর্ডার আইডি' },
  'orders.customer': { en: 'Customer', bn: 'কাস্টমার' },
  'orders.orderDate': { en: 'Order Date', bn: 'অর্ডার তারিখ' },
  'orders.orderStatus': { en: 'Order Status', bn: 'অর্ডার স্ট্যাটাস' },
  'orders.pending': { en: 'Pending', bn: 'পেন্ডিং' },
  'orders.processing': { en: 'Processing', bn: 'প্রসেসিং' },
  'orders.shipped': { en: 'Shipped', bn: 'শিপড' },
  'orders.delivered': { en: 'Delivered', bn: 'ডেলিভার্ড' },
  'orders.cancelled': { en: 'Cancelled', bn: 'বাতিল' },

  // Customers
  'customers.title': { en: 'Customers', bn: 'কাস্টমার' },
  'customers.totalCustomers': { en: 'Total Customers', bn: 'মোট কাস্টমার' },
  'customers.newCustomers': { en: 'New Customers', bn: 'নতুন কাস্টমার' },
  'customers.loyaltyTier': { en: 'Loyalty Tier', bn: 'লয়্যালটি টিয়ার' },

  // Shipping
  'shipping.title': { en: 'Shipping Management', bn: 'শিপিং ম্যানেজমেন্ট' },
  'shipping.zones': { en: 'Shipping Zones', bn: 'শিপিং জোন' },
  'shipping.rates': { en: 'Rates Configuration', bn: 'রেট কনফিগারেশন' },
  'shipping.couriers': { en: 'Courier Integration', bn: 'কুরিয়ার ইন্টিগ্রেশন' },
  'shipping.tracking': { en: 'Delivery Tracking', bn: 'ডেলিভারি ট্র্যাকিং' },

  // Messages
  'messages.title': { en: 'Messages & Support', bn: 'মেসেজ ও সাপোর্ট' },
  'messages.liveChat': { en: 'Live Chat', bn: 'লাইভ চ্যাট' },
  'messages.tickets': { en: 'Support Tickets', bn: 'সাপোর্ট টিকেট' },
  'messages.newTicket': { en: 'New Ticket', bn: 'নতুন টিকেট' },

  // Reports
  'reports.title': { en: 'Reports', bn: 'রিপোর্ট' },
  'reports.generate': { en: 'Generate Report', bn: 'রিপোর্ট জেনারেট' },
  'reports.scheduled': { en: 'Scheduled Reports', bn: 'শিডিউলড রিপোর্ট' },
  'reports.templates': { en: 'Templates', bn: 'টেমপ্লেট' },

  // Inventory
  'inventory.title': { en: 'Inventory Management', bn: 'ইনভেন্টরি ম্যানেজমেন্ট' },
  'inventory.stockLevels': { en: 'Stock Levels', bn: 'স্টক লেভেল' },
  'inventory.alerts': { en: 'Alerts', bn: 'অ্যালার্ট' },
  'inventory.suppliers': { en: 'Suppliers', bn: 'সাপ্লায়ার' },
  'inventory.purchaseOrders': { en: 'Purchase Orders', bn: 'পার্চেজ অর্ডার' },

  // Coupons
  'coupons.title': { en: 'Discounts & Coupons', bn: 'ডিসকাউন্ট ও কুপন' },
  'coupons.newCoupon': { en: 'New Coupon', bn: 'নতুন কুপন' },
  'coupons.autoRules': { en: 'Auto Rules', bn: 'অটো রুল' },
  'coupons.usageRecords': { en: 'Usage Records', bn: 'ব্যবহার রেকর্ড' },

  // Settings
  'settings.title': { en: 'Settings', bn: 'সেটিংস' },
  'settings.storeInfo': { en: 'Store Information', bn: 'স্টোর তথ্য' },
  'settings.payment': { en: 'Payment Gateways', bn: 'পেমেন্ট গেটওয়ে' },
  'settings.email': { en: 'Email Templates', bn: 'ইমেইল টেমপ্লেট' },
  'settings.notifications': { en: 'Notifications', bn: 'নোটিফিকেশন' },
  'settings.language': { en: 'Language', bn: 'ভাষা' },
  'settings.saveChanges': { en: 'Save Changes', bn: 'পরিবর্তন সেভ করুন' },

  // Analytics
  'analytics.title': { en: 'Analytics', bn: 'অ্যানালিটিক্স' },
  'analytics.revenue': { en: 'Revenue', bn: 'রেভিনিউ' },
  'analytics.profit': { en: 'Profit', bn: 'প্রফিট' },
  'analytics.visitors': { en: 'Visitors', bn: 'ভিজিটর' },
  'analytics.conversion': { en: 'Conversion Rate', bn: 'কনভার্সন রেট' },

  // Header
  'header.search': { en: 'Search...', bn: 'খুঁজুন...' },
  'header.notifications': { en: 'Notifications', bn: 'নোটিফিকেশন' },
  'header.profile': { en: 'Profile', bn: 'প্রোফাইল' },

  // Authentication
  'login': { en: 'Login', bn: 'লগইন' },
  'logout': { en: 'Logout', bn: 'লগআউট' },
  'createAccount': { en: 'Create Account', bn: 'অ্যাকাউন্ট তৈরি করুন' },
  'resetPassword': { en: 'Reset Password', bn: 'পাসওয়ার্ড রিসেট' },
  'updatePassword': { en: 'Update Password', bn: 'পাসওয়ার্ড আপডেট' },
  'loginDescription': { en: 'Enter your credentials to access the admin panel', bn: 'অ্যাডমিন প্যানেলে প্রবেশ করতে আপনার তথ্য দিন' },
  'signupDescription': { en: 'Create a new admin account', bn: 'নতুন অ্যাডমিন অ্যাকাউন্ট তৈরি করুন' },
  'resetDescription': { en: 'Enter your email to receive a reset link', bn: 'রিসেট লিংক পেতে আপনার ইমেইল দিন' },
  'updatePasswordDescription': { en: 'Enter your new password', bn: 'আপনার নতুন পাসওয়ার্ড দিন' },
  'email': { en: 'Email', bn: 'ইমেইল' },
  'password': { en: 'Password', bn: 'পাসওয়ার্ড' },
  'newPassword': { en: 'New Password', bn: 'নতুন পাসওয়ার্ড' },
  'confirmPassword': { en: 'Confirm Password', bn: 'পাসওয়ার্ড নিশ্চিত করুন' },
  'fullName': { en: 'Full Name', bn: 'পুরো নাম' },
  'forgotPassword': { en: 'Forgot password?', bn: 'পাসওয়ার্ড ভুলে গেছেন?' },
  'noAccount': { en: "Don't have an account?", bn: 'অ্যাকাউন্ট নেই?' },
  'signUp': { en: 'Sign up', bn: 'সাইন আপ' },
  'alreadyHaveAccount': { en: 'Already have an account?', bn: 'ইতিমধ্যে অ্যাকাউন্ট আছে?' },
  'backToLogin': { en: 'Back to Login', bn: 'লগইনে ফিরে যান' },
  'sendResetLink': { en: 'Send Reset Link', bn: 'রিসেট লিংক পাঠান' },
  'loginFailed': { en: 'Login Failed', bn: 'লগইন ব্যর্থ' },
  'invalidCredentials': { en: 'Invalid email or password', bn: 'ভুল ইমেইল বা পাসওয়ার্ড' },
  'loginSuccess': { en: 'Login Successful', bn: 'লগইন সফল' },
  'welcomeBack': { en: 'Welcome back!', bn: 'স্বাগতম!' },
  'signupFailed': { en: 'Signup Failed', bn: 'সাইন আপ ব্যর্থ' },
  'emailAlreadyRegistered': { en: 'This email is already registered', bn: 'এই ইমেইল ইতিমধ্যে নিবন্ধিত' },
  'signupSuccess': { en: 'Signup Successful', bn: 'সাইন আপ সফল' },
  'accountCreated': { en: 'Your account has been created', bn: 'আপনার অ্যাকাউন্ট তৈরি হয়েছে' },
  'resetFailed': { en: 'Reset Failed', bn: 'রিসেট ব্যর্থ' },
  'resetEmailSent': { en: 'Reset Email Sent', bn: 'রিসেট ইমেইল পাঠানো হয়েছে' },
  'checkYourEmail': { en: 'Check your email for the reset link', bn: 'রিসেট লিংকের জন্য আপনার ইমেইল চেক করুন' },
  'updatePasswordFailed': { en: 'Update Failed', bn: 'আপডেট ব্যর্থ' },
  'passwordUpdated': { en: 'Password Updated', bn: 'পাসওয়ার্ড আপডেট হয়েছে' },
  'passwordUpdateSuccess': { en: 'Your password has been updated', bn: 'আপনার পাসওয়ার্ড আপডেট হয়েছে' },
  'auth.orContinueWith': { en: 'Or continue with', bn: 'অথবা দিয়ে চালিয়ে যান' },
  'auth.continueWithGoogle': { en: 'Continue with Google', bn: 'Google দিয়ে চালিয়ে যান' },

  // Profile
  'profile.title': { en: 'Profile Settings', bn: 'প্রোফাইল সেটিংস' },
  'profile.subtitle': { en: 'Manage your account settings and preferences', bn: 'আপনার অ্যাকাউন্ট সেটিংস এবং পছন্দ পরিচালনা করুন' },
  'profile.avatar': { en: 'Profile Picture', bn: 'প্রোফাইল ছবি' },
  'profile.avatarDesc': { en: 'Upload a new profile picture', bn: 'একটি নতুন প্রোফাইল ছবি আপলোড করুন' },
  'profile.changeAvatar': { en: 'Change Avatar', bn: 'অ্যাভাটার পরিবর্তন' },
  'profile.uploading': { en: 'Uploading...', bn: 'আপলোড হচ্ছে...' },
  'profile.avatarUpdated': { en: 'Avatar Updated', bn: 'অ্যাভাটার আপডেট হয়েছে' },
  'profile.avatarUpdatedDesc': { en: 'Your profile picture has been updated', bn: 'আপনার প্রোফাইল ছবি আপডেট হয়েছে' },
  'profile.uploadFailed': { en: 'Upload Failed', bn: 'আপলোড ব্যর্থ' },
  'profile.personalInfo': { en: 'Personal Information', bn: 'ব্যক্তিগত তথ্য' },
  'profile.personalInfoDesc': { en: 'Update your personal details', bn: 'আপনার ব্যক্তিগত বিবরণ আপডেট করুন' },
  'profile.profileUpdated': { en: 'Profile Updated', bn: 'প্রোফাইল আপডেট হয়েছে' },
  'profile.profileUpdatedDesc': { en: 'Your profile has been updated', bn: 'আপনার প্রোফাইল আপডেট হয়েছে' },
  'profile.updateFailed': { en: 'Update Failed', bn: 'আপডেট ব্যর্থ' },
  'profile.changePassword': { en: 'Change Password', bn: 'পাসওয়ার্ড পরিবর্তন' },
  'profile.changePasswordDesc': { en: 'Update your password for security', bn: 'নিরাপত্তার জন্য আপনার পাসওয়ার্ড আপডেট করুন' },
  'profile.currentPassword': { en: 'Current Password', bn: 'বর্তমান পাসওয়ার্ড' },
  'profile.updatePassword': { en: 'Update Password', bn: 'পাসওয়ার্ড আপডেট' },
  'profile.passwordChanged': { en: 'Password Changed', bn: 'পাসওয়ার্ড পরিবর্তিত' },
  'profile.passwordChangedDesc': { en: 'Your password has been updated successfully', bn: 'আপনার পাসওয়ার্ড সফলভাবে আপডেট হয়েছে' },
  'profile.passwordFailed': { en: 'Password Update Failed', bn: 'পাসওয়ার্ড আপডেট ব্যর্থ' },

  // Role Management
  'roles.title': { en: 'Role Management', bn: 'রোল ম্যানেজমেন্ট' },
  'roles.subtitle': { en: 'Manage user roles and permissions', bn: 'ব্যবহারকারীর রোল এবং অনুমতি পরিচালনা করুন' },
  'roles.users': { en: 'Users', bn: 'ব্যবহারকারী' },
  'roles.admins': { en: 'Admins', bn: 'অ্যাডমিন' },
  'roles.superAdmins': { en: 'Super Admins', bn: 'সুপার অ্যাডমিন' },
  'roles.usersList': { en: 'All Users', bn: 'সব ব্যবহারকারী' },
  'roles.usersListDesc': { en: 'View and manage all user roles', bn: 'সব ব্যবহারকারীর রোল দেখুন এবং পরিচালনা করুন' },
  'roles.searchUsers': { en: 'Search users...', bn: 'ব্যবহারকারী খুঁজুন...' },
  'roles.user': { en: 'User', bn: 'ব্যবহারকারী' },
  'roles.role': { en: 'Role', bn: 'রোল' },
  'roles.changeRole': { en: 'Change Role', bn: 'রোল পরিবর্তন' },
  'roles.changeRoleTitle': { en: 'Change User Role', bn: 'ব্যবহারকারীর রোল পরিবর্তন' },
  'roles.changeRoleDesc': { en: 'Select a new role for', bn: 'নতুন রোল নির্বাচন করুন' },
  'roles.roleUpdated': { en: 'Role Updated', bn: 'রোল আপডেট হয়েছে' },
  'roles.roleUpdatedTo': { en: 'role changed to', bn: 'রোল পরিবর্তন হয়েছে' },
  'roles.updateFailed': { en: 'Update Failed', bn: 'আপডেট ব্যর্থ' },
  'roles.fetchFailed': { en: 'Failed to fetch users', bn: 'ব্যবহারকারী লোড করতে ব্যর্থ' },
  'roles.noUsers': { en: 'No users found', bn: 'কোন ব্যবহারকারী পাওয়া যায়নি' },
  'roles.unnamed': { en: 'Unnamed', bn: 'নামহীন' },
  'roles.accessDenied': { en: 'Access Denied', bn: 'অ্যাক্সেস অস্বীকৃত' },
  'roles.accessDeniedDesc': { en: 'Only Super Admins can access role management. Please contact a Super Admin if you need access.', bn: 'শুধুমাত্র সুপার অ্যাডমিনরা রোল ম্যানেজমেন্ট অ্যাক্সেস করতে পারেন।' },

  // ════════════ STORE FRONTEND ════════════

  // Store Header
  'store.searchPlaceholder': { en: 'Search for products...', bn: 'পণ্য খুঁজুন...' },
  'store.allCategories': { en: 'All Categories', bn: 'সব ক্যাটাগরি' },
  'store.myAccount': { en: 'My Account', bn: 'আমার অ্যাকাউন্ট' },
  'store.myOrders': { en: 'My Orders', bn: 'আমার অর্ডার' },
  'store.dashboard': { en: 'Dashboard', bn: 'ড্যাশবোর্ড' },

  // Store Navigation
  'store.home': { en: 'Home', bn: 'হোম' },
  'store.shop': { en: 'Shop', bn: 'শপ' },
  'store.wishlist': { en: 'Wishlist', bn: 'ইচ্ছা তালিকা' },
  'store.cart': { en: 'Cart', bn: 'কার্ট' },
  'store.account': { en: 'Account', bn: 'অ্যাকাউন্ট' },
  'store.contactUs': { en: 'Contact Us', bn: 'যোগাযোগ করুন' },
  'store.trackOrder': { en: 'Track Order', bn: 'অর্ডার ট্র্যাক করুন' },
  'store.shippingInfo': { en: 'Shipping Info', bn: 'শিপিং তথ্য' },

  // Store Home
  'store.featuredProducts': { en: 'Featured Products', bn: 'ফিচার্ড পণ্য' },
  'store.newArrivals': { en: 'New Arrivals', bn: 'নতুন আগমন' },
  'store.flashSale': { en: 'Flash Sale', bn: 'ফ্ল্যাশ সেল' },
  'store.shopNow': { en: 'Shop Now', bn: 'এখনই কিনুন' },
  'store.viewAll': { en: 'View All', bn: 'সব দেখুন' },
  'store.bestSellers': { en: 'Best Sellers', bn: 'সেরা বিক্রিত' },
  'store.shopByCategory': { en: 'Shop by Category', bn: 'ক্যাটাগরি অনুযায়ী কিনুন' },
  'store.freeShipping': { en: 'Free Shipping', bn: 'ফ্রি শিপিং' },
  'store.securePayment': { en: 'Secure Payment', bn: 'নিরাপদ পেমেন্ট' },
  'store.easyReturns': { en: 'Easy Returns', bn: 'সহজ রিটার্ন' },
  'store.support247': { en: '24/7 Support', bn: '২৪/৭ সাপোর্ট' },
  'store.noProductsYet': { en: 'No products available yet.', bn: 'এখনো কোন পণ্য পাওয়া যায়নি।' },
  'store.browseAllProducts': { en: 'Browse All Products', bn: 'সব পণ্য দেখুন' },
  'store.stayInLoop': { en: 'Stay in the Loop', bn: 'আপডেট থাকুন' },
  'store.subscribeNewsletter': { en: 'Subscribe to our newsletter for exclusive deals and new arrivals.', bn: 'এক্সক্লুসিভ ডিল ও নতুন পণ্যের জন্য আমাদের নিউজলেটারে সাবস্ক্রাইব করুন।' },
  'store.subscribe': { en: 'Subscribe', bn: 'সাবস্ক্রাইব' },
  'store.enterEmail': { en: 'Enter your email', bn: 'আপনার ইমেইল দিন' },

  // Product Listing / Filters
  'store.filters': { en: 'Filters', bn: 'ফিল্টার' },
  'store.clearFilters': { en: 'Clear Filters', bn: 'ফিল্টার মুছুন' },
  'store.sortBy': { en: 'Sort by', bn: 'সাজান' },
  'store.newest': { en: 'Newest', bn: 'নতুন' },
  'store.priceLowHigh': { en: 'Price: Low to High', bn: 'মূল্য: কম থেকে বেশি' },
  'store.priceHighLow': { en: 'Price: High to Low', bn: 'মূল্য: বেশি থেকে কম' },
  'store.nameAZ': { en: 'Name A-Z', bn: 'নাম A-Z' },
  'store.inStock': { en: 'In Stock', bn: 'স্টকে আছে' },
  'store.outOfStock': { en: 'Out of Stock', bn: 'স্টক শেষ' },
  'store.brand': { en: 'Brand', bn: 'ব্র্যান্ড' },
  'store.color': { en: 'Color', bn: 'রঙ' },
  'store.size': { en: 'Size', bn: 'সাইজ' },
  'store.rating': { en: 'Rating', bn: 'রেটিং' },
  'store.priceRange': { en: 'Price Range', bn: 'মূল্য সীমা' },
  'store.onSale': { en: 'On Sale', bn: 'সেলে আছে' },
  'store.noProductsFound': { en: 'No products found', bn: 'কোনো পণ্য পাওয়া যায়নি' },
  'store.tryDifferentFilters': { en: 'Try adjusting your filters or search terms.', bn: 'ফিল্টার বা সার্চ পরিবর্তন করে দেখুন।' },
  'store.stockStatus': { en: 'Stock Status', bn: 'স্টক স্ট্যাটাস' },
  'store.tags': { en: 'Tags', bn: 'ট্যাগ' },
  'store.products': { en: 'Products', bn: 'পণ্য' },

  // Product Detail
  'store.addToCart': { en: 'Add to Cart', bn: 'কার্টে যোগ করুন' },
  'store.addToWishlist': { en: 'Add to Wishlist', bn: 'ইচ্ছা তালিকায় যোগ করুন' },
  'store.buyNow': { en: 'Buy Now', bn: 'এখনই কিনুন' },
  'store.description': { en: 'Description', bn: 'বিবরণ' },
  'store.reviews': { en: 'Reviews', bn: 'রিভিউ' },
  'store.relatedProducts': { en: 'Related Products', bn: 'সম্পর্কিত পণ্য' },
  'store.sizeGuide': { en: 'Size Guide', bn: 'সাইজ গাইড' },
  'store.quantity': { en: 'Quantity', bn: 'পরিমাণ' },
  'store.sale': { en: 'Sale', bn: 'সেল' },
  'store.new': { en: 'New', bn: 'নতুন' },
  'store.soldOut': { en: 'Sold Out', bn: 'বিক্রি শেষ' },
  'store.add': { en: 'Add', bn: 'যোগ করুন' },

  // Cart & Checkout
  'store.shoppingCart': { en: 'Shopping Cart', bn: 'শপিং কার্ট' },
  'store.cartEmpty': { en: 'Your cart is empty', bn: 'আপনার কার্ট খালি' },
  'store.cartEmptyDesc': { en: "Looks like you haven't added anything to your cart yet. Start shopping to fill it up!", bn: 'মনে হচ্ছে আপনি এখনো কার্টে কিছু যোগ করেননি। কেনাকাটা শুরু করুন!' },
  'store.continueShopping': { en: 'Continue Shopping', bn: 'কেনাকাটা চালিয়ে যান' },
  'store.startShopping': { en: 'Start Shopping', bn: 'কেনাকাটা শুরু করুন' },
  'store.subtotal': { en: 'Subtotal', bn: 'সাবটোটাল' },
  'store.shipping': { en: 'Shipping', bn: 'শিপিং' },
  'store.total': { en: 'Total', bn: 'মোট' },
  'store.proceedToCheckout': { en: 'Proceed to Checkout', bn: 'চেকআউটে যান' },
  'store.checkout': { en: 'Checkout', bn: 'চেকআউট' },
  'store.placeOrder': { en: 'Place Order', bn: 'অর্ডার দিন' },
  'store.paymentMethod': { en: 'Payment Method', bn: 'পেমেন্ট পদ্ধতি' },
  'store.shippingAddress': { en: 'Shipping Address', bn: 'শিপিং ঠিকানা' },
  'store.orderSummary': { en: 'Order Summary', bn: 'অর্ডার সারাংশ' },
  'store.viewCart': { en: 'View Cart', bn: 'কার্ট দেখুন' },
  'store.clearCart': { en: 'Clear Cart', bn: 'কার্ট খালি করুন' },
  'store.share': { en: 'Share', bn: 'শেয়ার করুন' },
  'store.saveForLater': { en: 'Save for Later', bn: 'পরে জন্য সংরক্ষণ' },
  'store.moveToCart': { en: 'Move to Cart', bn: 'কার্টে সরান' },
  'store.savedForLater': { en: 'Saved for Later', bn: 'পরে জন্য সংরক্ষিত' },
  'store.addNote': { en: 'Add Note', bn: 'নোট যোগ করুন' },
  'store.editNote': { en: 'Edit Note', bn: 'নোট সম্পাদনা' },
  'store.estimatedDelivery': { en: 'Estimated delivery: 2-4 days', bn: 'আনুমানিক ডেলিভারি: ২-৪ দিন' },
  'store.shippingTaxNote': { en: 'Shipping and taxes calculated at checkout', bn: 'শিপিং ও ট্যাক্স চেকআউটে হিসাব হবে' },
  'store.discount': { en: 'Discount', bn: 'ডিসকাউন্ট' },
  'store.couponCode': { en: 'Coupon Code', bn: 'কুপন কোড' },
  'store.apply': { en: 'Apply', bn: 'প্রয়োগ করুন' },
  'store.remove': { en: 'Remove', bn: 'সরান' },
  'store.free': { en: 'Free', bn: 'ফ্রি' },
  'store.items': { en: 'items', bn: 'টি পণ্য' },
  'store.item': { en: 'item', bn: 'টি পণ্য' },
  'store.selected': { en: 'selected', bn: 'নির্বাচিত' },
  'store.inYourCart': { en: 'in your cart', bn: 'আপনার কার্টে' },

  // Wishlist Page
  'store.myWishlist': { en: 'My Wishlist', bn: 'আমার ইচ্ছা তালিকা' },
  'store.wishlistEmpty': { en: 'Your wishlist is empty', bn: 'আপনার ইচ্ছা তালিকা খালি' },
  'store.wishlistEmptyDesc': { en: 'Browse our products and click the heart icon to save items you love.', bn: 'পণ্য ব্রাউজ করুন এবং হার্ট আইকনে ক্লিক করে প্রিয় পণ্য সংরক্ষণ করুন।' },
  'store.browseProducts': { en: 'Browse Products', bn: 'পণ্য দেখুন' },
  'store.loginToViewWishlist': { en: 'Login to view your wishlist', bn: 'ইচ্ছা তালিকা দেখতে লগইন করুন' },
  'store.signInToSave': { en: 'Sign in to save your favorite products and access them anytime.', bn: 'প্রিয় পণ্য সংরক্ষণ করতে সাইন ইন করুন।' },
  'store.signIn': { en: 'Sign In', bn: 'সাইন ইন' },
  'store.itemsSaved': { en: 'items saved', bn: 'টি পণ্য সংরক্ষিত' },
  'store.itemSaved': { en: 'item saved', bn: 'টি পণ্য সংরক্ষিত' },

  // Account Sidebar
  'account.overview': { en: 'OVERVIEW', bn: 'সারসংক্ষেপ' },
  'account.orders': { en: 'ORDERS', bn: 'অর্ডার' },
  'account.shopping': { en: 'SHOPPING', bn: 'কেনাকাটা' },
  'account.accountSection': { en: 'ACCOUNT', bn: 'অ্যাকাউন্ট' },
  'account.help': { en: 'HELP', bn: 'সাহায্য' },
  'account.dashboard': { en: 'Dashboard', bn: 'ড্যাশবোর্ড' },
  'account.notifications': { en: 'Notifications', bn: 'নোটিফিকেশন' },
  'account.myOrders': { en: 'My Orders', bn: 'আমার অর্ডার' },
  'account.returns': { en: 'Returns', bn: 'রিটার্ন' },
  'account.wishlist': { en: 'Wishlist', bn: 'ইচ্ছা তালিকা' },
  'account.shoppingLink': { en: 'Shopping', bn: 'কেনাকাটা' },
  'account.recentlyViewed': { en: 'Recently Viewed', bn: 'সম্প্রতি দেখা' },
  'account.myReviews': { en: 'My Reviews', bn: 'আমার রিভিউ' },
  'account.addresses': { en: 'Addresses', bn: 'ঠিকানা' },
  'account.paymentMethods': { en: 'Payment Methods', bn: 'পেমেন্ট পদ্ধতি' },
  'account.security': { en: 'Security', bn: 'নিরাপত্তা' },
  'account.settings': { en: 'Settings', bn: 'সেটিংস' },
  'account.support': { en: 'Support', bn: 'সাপোর্ট' },
  'account.liveChat': { en: 'Live Chat', bn: 'লাইভ চ্যাট' },
  'account.backToStore': { en: 'Back to Store', bn: 'স্টোরে ফিরে যান' },
  'account.signOut': { en: 'Sign Out', bn: 'সাইন আউট' },
  'account.collapse': { en: 'Collapse', bn: 'সংকুচিত' },

  // Account Page Titles
  'account.dashboardDesc': { en: 'Overview of your account activity', bn: 'আপনার অ্যাকাউন্ট কার্যকলাপের সারসংক্ষেপ' },
  'account.ordersTitle': { en: 'My Orders', bn: 'আমার অর্ডার' },
  'account.ordersDesc': { en: 'View and track your orders', bn: 'আপনার অর্ডার দেখুন ও ট্র্যাক করুন' },
  'account.returnsTitle': { en: 'Returns & Refunds', bn: 'রিটার্ন ও রিফান্ড' },
  'account.returnsDesc': { en: 'Submit return or refund requests', bn: 'রিটার্ন বা রিফান্ড অনুরোধ জমা দিন' },
  'account.wishlistTitle': { en: 'Wishlist', bn: 'ইচ্ছা তালিকা' },
  'account.wishlistDesc': { en: "Products you've saved for later", bn: 'পরে জন্য সংরক্ষিত পণ্য' },
  'account.shoppingTitle': { en: 'Shopping', bn: 'কেনাকাটা' },
  'account.shoppingDesc': { en: 'Buy again, coupons & deals', bn: 'আবার কিনুন, কুপন ও ডিল' },
  'account.recentlyViewedTitle': { en: 'Recently Viewed', bn: 'সম্প্রতি দেখা' },
  'account.recentlyViewedDesc': { en: "Products you've browsed", bn: 'আপনি যে পণ্যগুলো দেখেছেন' },
  'account.reviewsTitle': { en: 'My Reviews', bn: 'আমার রিভিউ' },
  'account.reviewsDesc': { en: 'Your product reviews & ratings', bn: 'আপনার পণ্য রিভিউ ও রেটিং' },
  'account.addressesTitle': { en: 'Addresses', bn: 'ঠিকানা' },
  'account.addressesDesc': { en: 'Manage delivery addresses', bn: 'ডেলিভারি ঠিকানা পরিচালনা করুন' },
  'account.paymentTitle': { en: 'Payment Methods', bn: 'পেমেন্ট পদ্ধতি' },
  'account.paymentDesc': { en: 'Manage saved payment methods', bn: 'সংরক্ষিত পেমেন্ট পদ্ধতি পরিচালনা করুন' },
  'account.securityTitle': { en: 'Security', bn: 'নিরাপত্তা' },
  'account.securityDesc': { en: 'Account protection settings', bn: 'অ্যাকাউন্ট সুরক্ষা সেটিংস' },
  'account.supportTitle': { en: 'Support', bn: 'সাপোর্ট' },
  'account.supportDesc': { en: 'Get help from our team', bn: 'আমাদের টিম থেকে সাহায্য নিন' },
  'account.chatTitle': { en: 'Live Chat', bn: 'লাইভ চ্যাট' },
  'account.chatDesc': { en: 'Chat with our support team', bn: 'সাপোর্ট টিমের সাথে চ্যাট করুন' },
  'account.notificationsTitle': { en: 'Notifications', bn: 'নোটিফিকেশন' },
  'account.notificationsDesc': { en: 'All your notifications in one place', bn: 'আপনার সব নোটিফিকেশন এক জায়গায়' },
  'account.settingsTitle': { en: 'Settings', bn: 'সেটিংস' },
  'account.settingsDesc': { en: 'Profile & preferences', bn: 'প্রোফাইল ও পছন্দ' },

  // Footer
  'store.shopFooter': { en: 'Shop', bn: 'শপ' },
  'store.helpFooter': { en: 'Help', bn: 'সাহায্য' },
  'store.contact': { en: 'Contact', bn: 'যোগাযোগ' },
  'store.allProducts': { en: 'All Products', bn: 'সব পণ্য' },
  'store.privacyPolicy': { en: 'Privacy Policy', bn: 'গোপনীয়তা নীতি' },
  'store.termsOfService': { en: 'Terms of Service', bn: 'সেবার শর্তাবলী' },
  'store.allRightsReserved': { en: 'All rights reserved.', bn: 'সর্বস্বত্ব সংরক্ষিত।' },
  'store.faq': { en: 'FAQs', bn: 'প্রশ্নোত্তর' },
  'store.returnsExchange': { en: 'Returns & Exchange', bn: 'রিটার্ন ও এক্সচেঞ্জ' },

  // Contact Page
  'store.contactTitle': { en: 'Contact Us', bn: 'যোগাযোগ করুন' },
  'store.contactSubtitle': { en: "Have questions? We'd love to hear from you.", bn: 'প্রশ্ন আছে? আমরা আপনার কাছ থেকে শুনতে চাই।' },
  'store.sendMessage': { en: 'Send Message', bn: 'মেসেজ পাঠান' },
  'store.sendUsMessage': { en: 'Send us a message', bn: 'আমাদের মেসেজ পাঠান' },
  'store.firstName': { en: 'First Name', bn: 'প্রথম নাম' },
  'store.lastName': { en: 'Last Name', bn: 'শেষ নাম' },
  'store.phoneOptional': { en: 'Phone (Optional)', bn: 'ফোন (ঐচ্ছিক)' },
  'store.message': { en: 'Message', bn: 'মেসেজ' },
  'store.sending': { en: 'Sending...', bn: 'পাঠানো হচ্ছে...' },

  // FAQ Page
  'store.faqTitle': { en: 'Frequently Asked Questions', bn: 'সাধারণ জিজ্ঞাসা' },
  'store.faqSubtitle': { en: 'Find answers to common questions about our products, shipping, returns, and more.', bn: 'আমাদের পণ্য, শিপিং, রিটার্ন ইত্যাদি সম্পর্কে সাধারণ প্রশ্নের উত্তর খুঁজুন।' },

  // Shipping Info Page
  'store.shippingInfoTitle': { en: 'Shipping Information', bn: 'শিপিং তথ্য' },
  'store.shippingInfoSubtitle': { en: 'Everything you need to know about our shipping policies and delivery times.', bn: 'আমাদের শিপিং নীতি ও ডেলিভারি সময় সম্পর্কে সব তথ্য।' },

  // Returns Page
  'store.returnsTitle': { en: 'Returns & Exchange', bn: 'রিটার্ন ও এক্সচেঞ্জ' },
  'store.returnsSubtitle': { en: 'We want you to be completely satisfied with your purchase.', bn: 'আমরা চাই আপনার কেনাকাটা নিয়ে সম্পূর্ণ সন্তুষ্ট থাকুন।' },

  // Privacy & Terms
  'store.privacyTitle': { en: 'Privacy Policy', bn: 'গোপনীয়তা নীতি' },
  'store.termsTitle': { en: 'Terms of Service', bn: 'সেবার শর্তাবলী' },

  // Size / Color labels used in cart
  'store.sizeLabel': { en: 'Size', bn: 'সাইজ' },
  'store.colorLabel': { en: 'Color', bn: 'রঙ' },

  // Sticky bar
  'store.addShort': { en: 'Add', bn: 'যোগ' },

  // ════════════ PRODUCT DETAIL PAGE ════════════
  'store.productNotFound': { en: 'Product Not Found', bn: 'পণ্য পাওয়া যায়নি' },
  'store.productNotFoundDesc': { en: "The product you're looking for doesn't exist.", bn: 'আপনি যে পণ্যটি খুঁজছেন তা বিদ্যমান নেই।' },
  'store.backToProducts': { en: 'Back to Products', bn: 'পণ্যে ফিরে যান' },
  'store.limitedTimeOffer': { en: 'Limited Time Offer', bn: 'সীমিত সময়ের অফার' },
  'store.notifyWhenAvailable': { en: 'Notify When Available', bn: 'পাওয়া গেলে জানান' },
  'store.notifyMe': { en: 'Notify Me', bn: 'আমাকে জানান' },
  'store.yourEmail': { en: 'Your email', bn: 'আপনার ইমেইল' },
  'store.selectVariant': { en: 'Select Variant', bn: 'ভেরিয়েন্ট নির্বাচন করুন' },
  'store.thisBundleIncludes': { en: 'This bundle includes', bn: 'এই বান্ডেলে অন্তর্ভুক্ত' },
  'store.productsInGroup': { en: 'Products in this group', bn: 'এই গ্রুপের পণ্য' },
  'store.specifications': { en: 'Specifications', bn: 'স্পেসিফিকেশন' },
  'store.noDescriptionAvailable': { en: 'No description available.', bn: 'কোনো বিবরণ পাওয়া যায়নি।' },
  'store.compareProducts': { en: 'Compare Products', bn: 'পণ্য তুলনা করুন' },
  'store.feature': { en: 'Feature', bn: 'বৈশিষ্ট্য' },
  'store.category': { en: 'Category', bn: 'ক্যাটাগরি' },
  'store.available': { en: 'Available', bn: 'পাওয়া যাচ্ছে' },
  'store.addedToCart': { en: 'Added to cart!', bn: 'কার্টে যোগ হয়েছে!' },
  'store.bundleAddedToCart': { en: 'Bundle added to cart!', bn: 'বান্ডেল কার্টে যোগ হয়েছে!' },
  'store.pleaseSelectVariant': { en: 'Please select a variant', bn: 'অনুগ্রহ করে একটি ভেরিয়েন্ট নির্বাচন করুন' },
  'store.pleaseSelectProduct': { en: 'Please select at least one product', bn: 'অনুগ্রহ করে কমপক্ষে একটি পণ্য নির্বাচন করুন' },
  'store.linkCopied': { en: 'Link copied!', bn: 'লিংক কপি হয়েছে!' },
  'store.skuCopied': { en: 'SKU copied!', bn: 'SKU কপি হয়েছে!' },
  'store.onlyLeftInStock': { en: 'left in stock — order soon!', bn: 'টি স্টকে আছে — দ্রুত অর্ডার করুন!' },
  'store.notifySuccess': { en: "We'll notify you when this product is back in stock!", bn: 'পণ্যটি স্টকে আসলে আমরা আপনাকে জানাব!' },
  'store.enterEmailError': { en: 'Please enter your email', bn: 'অনুগ্রহ করে আপনার ইমেইল দিন' },
  'store.itemsAddedToCart': { en: 'items added to cart!', bn: 'টি পণ্য কার্টে যোগ হয়েছে!' },
  'store.fullGuide': { en: 'Full guide', bn: 'সম্পূর্ণ গাইড' },
  'store.compare': { en: 'Compare', bn: 'তুলনা' },
  'store.viewFullDetails': { en: 'View Full Details', bn: 'সম্পূর্ণ বিবরণ দেখুন' },
  'store.simple': { en: 'Simple', bn: 'সাধারণ' },
  'store.variable': { en: 'Variable', bn: 'ভেরিয়েবল' },
  'store.grouped': { en: 'Grouped', bn: 'গ্রুপড' },
  'store.bundle': { en: 'Bundle', bn: 'বান্ডেল' },
  'store.selectProducts': { en: 'Select Products', bn: 'পণ্য নির্বাচন করুন' },
  'store.bundleIncludes': { en: 'Bundle Includes', bn: 'বান্ডেলে অন্তর্ভুক্ত' },
  'store.addBundleToCart': { en: 'Add Bundle to Cart', bn: 'বান্ডেল কার্টে যোগ করুন' },
  'store.addItems': { en: 'Add Items', bn: 'পণ্য যোগ করুন' },
  'store.selectOptions': { en: 'Select Options', bn: 'অপশন নির্বাচন করুন' },
  'store.quickAdd': { en: 'Quick Add', bn: 'দ্রুত যোগ' },
  'store.uncategorized': { en: 'Uncategorized', bn: 'শ্রেণীবিহীন' },
  'store.from': { en: 'From', bn: 'শুরু' },
  'store.save': { en: 'Save', bn: 'সেভ' },

  // ════════════ PRODUCT REVIEWS ════════════
  'store.writeReview': { en: 'Write a Review', bn: 'রিভিউ লিখুন' },
  'store.writeYourReview': { en: 'Write Your Review', bn: 'আপনার রিভিউ লিখুন' },
  'store.ratingLabel': { en: 'Rating', bn: 'রেটিং' },
  'store.titleOptional': { en: 'Title (optional)', bn: 'শিরোনাম (ঐচ্ছিক)' },
  'store.review': { en: 'Review', bn: 'রিভিউ' },
  'store.submitReview': { en: 'Submit Review', bn: 'রিভিউ জমা দিন' },
  'store.submitting': { en: 'Submitting...', bn: 'জমা হচ্ছে...' },
  'store.verifiedPurchase': { en: 'Verified Purchase', bn: 'যাচাইকৃত ক্রয়' },
  'store.reviewSubmitted': { en: 'Review submitted! It will appear after approval.', bn: 'রিভিউ জমা হয়েছে! অনুমোদনের পর দেখা যাবে।' },
  'store.noReviewsYet': { en: 'No reviews yet. Be the first to review this product!', bn: 'এখনো কোনো রিভিউ নেই। প্রথম রিভিউ দিন!' },
  'store.onlyVerifiedBuyers': { en: 'Only verified buyers can write a review', bn: 'শুধুমাত্র যাচাইকৃত ক্রেতারা রিভিউ দিতে পারেন' },
  'store.loginToReview': { en: 'Please login to write a review', bn: 'রিভিউ লিখতে লগইন করুন' },
  'store.photosOptional': { en: 'Photos (optional, max 5)', bn: 'ছবি (ঐচ্ছিক, সর্বোচ্চ ৫)' },
  'store.videoOptional': { en: 'Video (optional, max 20MB)', bn: 'ভিডিও (ঐচ্ছিক, সর্বোচ্চ ২০MB)' },
  'store.addVideo': { en: 'Add Video', bn: 'ভিডিও যোগ করুন' },
  'store.uploadingMedia': { en: 'Uploading media...', bn: 'মিডিয়া আপলোড হচ্ছে...' },
  'store.summarizeExperience': { en: 'Summarize your experience', bn: 'আপনার অভিজ্ঞতা সংক্ষেপে লিখুন' },
  'store.tellOthers': { en: 'Tell others about your experience...', bn: 'অন্যদের আপনার অভিজ্ঞতা জানান...' },
  'store.star': { en: 'star', bn: 'তারা' },

  // ════════════ CHECKOUT ════════════
  'store.shippingInformation': { en: 'Shipping Information', bn: 'শিপিং তথ্য' },
  'store.billingAddress': { en: 'Billing Address', bn: 'বিলিং ঠিকানা' },
  'store.phoneNumber': { en: 'Phone Number', bn: 'ফোন নম্বর' },
  'store.city': { en: 'City', bn: 'শহর' },
  'store.postalCode': { en: 'Postal Code', bn: 'পোস্টাল কোড' },
  'store.orderNotes': { en: 'Order Notes (Optional)', bn: 'অর্ডার নোট (ঐচ্ছিক)' },
  'store.specialInstructions': { en: 'Special instructions for delivery', bn: 'ডেলিভারির জন্য বিশেষ নির্দেশনা' },
  'store.shippingZoneRate': { en: 'Shipping Zone & Rate', bn: 'শিপিং জোন ও রেট' },
  'store.deliveryOption': { en: 'Delivery Option', bn: 'ডেলিভারি অপশন' },
  'store.loadingShipping': { en: 'Loading shipping options...', bn: 'শিপিং অপশন লোড হচ্ছে...' },
  'store.sameAsShipping': { en: 'Same as shipping address', bn: 'শিপিং ঠিকানার মত' },
  'store.saveAddress': { en: 'Save this address for future orders', bn: 'ভবিষ্যতের অর্ডারের জন্য এই ঠিকানা সংরক্ষণ করুন' },
  'store.addressLabel': { en: 'Address Label', bn: 'ঠিকানার লেবেল' },
  'store.cashOnDelivery': { en: 'Cash on Delivery', bn: 'ক্যাশ অন ডেলিভারি' },
  'store.payWithCash': { en: 'Pay with cash when your order is delivered to your doorstep.', bn: 'অর্ডার ডেলিভারি হলে নগদ পরিশোধ করুন।' },
  'store.termsConditions': { en: 'Terms & Conditions', bn: 'শর্তাবলী' },
  'store.processing': { en: 'Processing...', bn: 'প্রসেসিং...' },
  'store.reviewPlaceOrder': { en: 'Review & Place Order', bn: 'রিভিউ ও অর্ডার দিন' },
  'store.secureCheckout': { en: 'Secure checkout', bn: 'নিরাপদ চেকআউট' },
  'store.autoDiscount': { en: 'Auto Discount', bn: 'অটো ডিসকাউন্ট' },
  'store.codCharge': { en: 'COD Charge', bn: 'COD চার্জ' },
  'store.orderMoreForFree': { en: 'more for free delivery!', bn: 'আরো অর্ডার করলে ফ্রি ডেলিভারি!' },
  'store.noPaymentMethods': { en: 'No payment methods available', bn: 'কোনো পেমেন্ট পদ্ধতি পাওয়া যায়নি' },
  'store.noShippingOptions': { en: 'No shipping options available for this zone', bn: 'এই জোনে কোনো শিপিং অপশন নেই' },
  'store.selectYourArea': { en: 'Select your area', bn: 'আপনার এলাকা নির্বাচন করুন' },
  'store.shippingZone': { en: 'Shipping Zone', bn: 'শিপিং জোন' },
  'store.homeLabel': { en: 'Home', bn: 'বাসা' },
  'store.officeLabel': { en: 'Office', bn: 'অফিস' },
  'store.otherLabel': { en: 'Other', bn: 'অন্যান্য' },
  'store.iAgreeToTerms': { en: 'I agree to the', bn: 'আমি সম্মত' },
  'store.and': { en: 'and', bn: 'এবং' },
  'store.fillRequiredFields': { en: 'Please fill in all required fields', bn: 'অনুগ্রহ করে সব প্রয়োজনীয় ঘর পূরণ করুন' },
  'store.validPhone': { en: 'Please enter a valid Bangladeshi phone number', bn: 'একটি বৈধ বাংলাদেশি ফোন নম্বর দিন' },
  'store.selectShippingZone': { en: 'Please select a shipping zone and delivery option', bn: 'শিপিং জোন ও ডেলিভারি অপশন নির্বাচন করুন' },
  'store.acceptTerms': { en: 'Please accept the Terms & Conditions', bn: 'শর্তাবলী গ্রহণ করুন' },
  'store.orderPlaced': { en: 'Order placed successfully!', bn: 'অর্ডার সফলভাবে দেওয়া হয়েছে!' },
  'store.addSomeProducts': { en: 'Add some products before checking out.', bn: 'চেকআউটের আগে কিছু পণ্য যোগ করুন।' },

  // ════════════ CHECKOUT STEPS ════════════
  'store.stepContact': { en: 'Contact', bn: 'যোগাযোগ' },
  'store.stepShipping': { en: 'Shipping', bn: 'শিপিং' },
  'store.stepPayment': { en: 'Payment', bn: 'পেমেন্ট' },
  'store.stepReview': { en: 'Review', bn: 'রিভিউ' },

  // ════════════ ORDER CONFIRMATION ════════════
  'store.thankYouOrder': { en: 'Thank You for Your Order!', bn: 'আপনার অর্ডারের জন্য ধন্যবাদ!' },
  'store.orderPlacedSuccess': { en: 'Your order has been placed successfully.', bn: 'আপনার অর্ডার সফলভাবে দেওয়া হয়েছে।' },
  'store.orderNumber': { en: 'Order Number', bn: 'অর্ডার নম্বর' },
  'store.estimatedDeliveryLabel': { en: 'Estimated Delivery', bn: 'আনুমানিক ডেলিভারি' },
  'store.orderItems': { en: 'Order Items', bn: 'অর্ডার আইটেম' },
  'store.whatsNext': { en: "What's Next?", bn: 'এরপর কী?' },
  'store.confirmationEmail': { en: 'You will receive an order confirmation email shortly', bn: 'শীঘ্রই একটি অর্ডার নিশ্চিতকরণ ইমেইল পাবেন' },
  'store.notifyShipment': { en: "We'll notify you when your order ships", bn: 'অর্ডার শিপ হলে আপনাকে জানানো হবে' },
  'store.trackInDashboard': { en: 'Track your order in your account dashboard', bn: 'আপনার অ্যাকাউন্ট ড্যাশবোর্ড থেকে অর্ডার ট্র্যাক করুন' },
  'store.paymentVerificationPending': { en: 'Payment verification pending', bn: 'পেমেন্ট যাচাই চলছে' },
  'store.paymentOnDelivery': { en: 'Payment will be collected upon delivery', bn: 'ডেলিভারির সময় পেমেন্ট নেওয়া হবে' },
  'store.viewAllOrders': { en: 'You can also view all your orders in your', bn: 'আপনি আপনার সব অর্ডার দেখতে পারেন আপনার' },
  'store.accountDashboard': { en: 'account dashboard', bn: 'অ্যাকাউন্ট ড্যাশবোর্ড' },

  // ════════════ AUTH (LOGIN/SIGNUP VIEW) ════════════
  'store.welcome': { en: 'Welcome', bn: 'স্বাগতম' },
  'store.signInOrCreate': { en: 'Sign in to your account or create a new one', bn: 'আপনার অ্যাকাউন্টে সাইন ইন করুন অথবা নতুন একটি তৈরি করুন' },
  'store.signInTab': { en: 'Sign In', bn: 'সাইন ইন' },
  'store.signUpTab': { en: 'Sign Up', bn: 'সাইন আপ' },
  'store.emailLabel': { en: 'Email', bn: 'ইমেইল' },
  'store.passwordLabel': { en: 'Password', bn: 'পাসওয়ার্ড' },
  'store.fullNameLabel': { en: 'Full Name', bn: 'পুরো নাম' },
  'store.forgotPasswordQ': { en: 'Forgot Password?', bn: 'পাসওয়ার্ড ভুলে গেছেন?' },
  'store.signingIn': { en: 'Signing in...', bn: 'সাইন ইন হচ্ছে...' },
  'store.creatingAccount': { en: 'Creating account...', bn: 'অ্যাকাউন্ট তৈরি হচ্ছে...' },
  'store.createAccountBtn': { en: 'Create Account', bn: 'অ্যাকাউন্ট তৈরি করুন' },
  'store.minChars': { en: 'Minimum 6 characters', bn: 'সর্বনিম্ন ৬ অক্ষর' },
  'store.or': { en: 'OR', bn: 'অথবা' },
  'store.continueGoogle': { en: 'Continue with Google', bn: 'Google দিয়ে চালিয়ে যান' },
  'store.byContinuing': { en: 'By continuing, you agree to our', bn: 'চালিয়ে যাওয়ার মাধ্যমে আপনি সম্মত হচ্ছেন আমাদের' },
  'store.backToStore': { en: 'Back to Store', bn: 'স্টোরে ফিরে যান' },

  // ════════════ STORE PRODUCTS FILTER PAGE ════════════
  'store.saleItems': { en: 'Sale Items', bn: 'সেলের পণ্য' },
  'store.productsAvailable': { en: 'products available', bn: 'টি পণ্য পাওয়া যাচ্ছে' },
  'store.searchProducts': { en: 'Search products...', bn: 'পণ্য খুঁজুন...' },
  'store.categories': { en: 'Categories', bn: 'ক্যাটাগরি' },
  'store.brands': { en: 'Brands', bn: 'ব্র্যান্ড' },
  'store.colors': { en: 'Colors', bn: 'রঙ' },
  'store.sizes': { en: 'Sizes', bn: 'সাইজ' },
  'store.availability': { en: 'Availability', bn: 'প্রাপ্যতা' },
  'store.quickFilters': { en: 'Quick Filters', bn: 'দ্রুত ফিল্টার' },
  'store.clearAll': { en: 'Clear All', bn: 'সব মুছুন' },
  'store.andUp': { en: '& Up', bn: 'ও উপরে' },

  // ════════════ STORE HOME DEFAULTS ════════════  
  'store.whatCustomersSay': { en: 'What Our Customers Say', bn: 'আমাদের কাস্টমাররা কী বলেন' },
  'store.styleInspiration': { en: 'Style Inspiration', bn: 'স্টাইল ইন্সপিরেশন' },
  'store.freeShippingDesc': { en: 'On orders over ৳2,000', bn: '৳২,০০০ এর বেশি অর্ডারে' },
  'store.securePaymentDesc': { en: '100% protected', bn: '১০০% সুরক্ষিত' },
  'store.easyReturnsDesc': { en: '7-day return policy', bn: '৭ দিনের রিটার্ন পলিসি' },
  'store.support247Desc': { en: 'Always here to help', bn: 'সবসময় সাহায্যে আছি' },
  'store.alreadySubscribed': { en: "You're already subscribed!", bn: 'আপনি ইতিমধ্যে সাবস্ক্রাইব করেছেন!' },
  'store.subscribedSuccess': { en: 'Successfully subscribed!', bn: 'সফলভাবে সাবস্ক্রাইব হয়েছে!' },
  'store.subscribeFailed': { en: 'Failed to subscribe. Please try again.', bn: 'সাবস্ক্রাইব ব্যর্থ। আবার চেষ্টা করুন।' },
  'store.validEmail': { en: 'Please enter a valid email address', bn: 'একটি বৈধ ইমেইল ঠিকানা দিন' },

  // ════════════ ACCOUNT PAGE ADDITIONAL ════════════
  'account.welcomeBack': { en: 'Welcome back', bn: 'স্বাগতম' },
  'account.accountActivity': { en: "Here's what's happening with your account.", bn: 'আপনার অ্যাকাউন্টে কী ঘটছে তা এখানে।' },
  'account.totalOrders': { en: 'Total Orders', bn: 'মোট অর্ডার' },
  'account.totalSpent': { en: 'Total Spent', bn: 'মোট খরচ' },
  'account.deliveredLabel': { en: 'Delivered', bn: 'ডেলিভার্ড' },
  'account.inTransit': { en: 'In Transit', bn: 'পথে আছে' },
  'account.pendingLabel': { en: 'Pending', bn: 'পেন্ডিং' },
  'account.recentOrders': { en: 'Recent Orders', bn: 'সাম্প্রতিক অর্ডার' },
  'account.viewAll': { en: 'View All', bn: 'সব দেখুন' },
  'account.noOrdersYet': { en: 'No orders yet', bn: 'এখনো কোনো অর্ডার নেই' },
  'account.startShopping': { en: 'Start Shopping', bn: 'কেনাকাটা শুরু করুন' },
  'account.addressesPageTitle': { en: 'Addresses', bn: 'ঠিকানা' },
  'account.manageAddresses': { en: 'Manage your shipping and billing addresses', bn: 'আপনার শিপিং ও বিলিং ঠিকানা পরিচালনা করুন' },
  'account.addAddress': { en: 'Add Address', bn: 'ঠিকানা যোগ করুন' },
  'account.noAddresses': { en: 'No addresses saved', bn: 'কোনো ঠিকানা সংরক্ষিত নেই' },
  'account.addForCheckout': { en: 'Add an address for faster checkout', bn: 'দ্রুত চেকআউটের জন্য একটি ঠিকানা যোগ করুন' },
  'account.editAddress': { en: 'Edit Address', bn: 'ঠিকানা সম্পাদনা' },
  'account.addNewAddress': { en: 'Add New Address', bn: 'নতুন ঠিকানা যোগ করুন' },
  'account.deleteAddress': { en: 'Delete Address?', bn: 'ঠিকানা মুছবেন?' },
  'account.defaultShipping': { en: 'Default Shipping', bn: 'ডিফল্ট শিপিং' },
  'account.defaultBilling': { en: 'Default Billing', bn: 'ডিফল্ট বিলিং' },
  'account.setDefault': { en: 'Set Default', bn: 'ডিফল্ট সেট করুন' },
  'account.ordersPageTitle': { en: 'My Orders', bn: 'আমার অর্ডার' },
  'account.viewManageOrders': { en: 'View and manage your order history', bn: 'আপনার অর্ডার ইতিহাস দেখুন ও পরিচালনা করুন' },
  'account.settingsPageTitle': { en: 'Settings', bn: 'সেটিংস' },
  'account.manageProfile': { en: 'Manage your profile, password, and notifications', bn: 'আপনার প্রোফাইল, পাসওয়ার্ড, ও নোটিফিকেশন পরিচালনা করুন' },
  'account.profileInfo': { en: 'Profile Information', bn: 'প্রোফাইল তথ্য' },
  'account.updatePersonalInfo': { en: 'Update your personal information', bn: 'আপনার ব্যক্তিগত তথ্য আপডেট করুন' },
  'account.changePassword': { en: 'Change Password', bn: 'পাসওয়ার্ড পরিবর্তন' },
  'account.updatePassword': { en: 'Update your account password', bn: 'আপনার অ্যাকাউন্টের পাসওয়ার্ড আপডেট করুন' },
  'account.notificationPrefs': { en: 'Notification Preferences', bn: 'নোটিফিকেশন পছন্দ' },
  'account.manageNotifications': { en: 'Manage your email notification settings', bn: 'আপনার ইমেইল নোটিফিকেশন সেটিংস পরিচালনা করুন' },
  'account.saveChanges': { en: 'Save Changes', bn: 'পরিবর্তন সেভ করুন' },
  'account.securityPageTitle': { en: 'Security', bn: 'নিরাপত্তা' },
  'account.manageSecuritySettings': { en: 'Manage your security settings and account protection', bn: 'আপনার নিরাপত্তা সেটিংস ও অ্যাকাউন্ট সুরক্ষা পরিচালনা করুন' },
  'account.supportPageTitle': { en: 'Support', bn: 'সাপোর্ট' },
  'account.getHelpFromTeam': { en: 'Get help from our support team', bn: 'আমাদের সাপোর্ট টিম থেকে সাহায্য নিন' },
  'account.shoppingPageTitle': { en: 'Shopping', bn: 'কেনাকাটা' },
  'account.shoppingPageDesc': { en: 'Buy again, coupons, and price alerts', bn: 'আবার কিনুন, কুপন, ও মূল্য সতর্কতা' },
  'account.recentlyViewedPageTitle': { en: 'Recently Viewed', bn: 'সম্প্রতি দেখা' },
  'account.recentlyViewedPageDesc': { en: "Products you've browsed recently", bn: 'সম্প্রতি আপনি যে পণ্যগুলো দেখেছেন' },

  // ════════════ PRODUCT DETAIL EXTRA ════════════
  'store.sizeGuide': { en: 'Size Guide', bn: 'সাইজ গাইড' },
  'store.chest': { en: 'Chest', bn: 'বুক' },
  'store.waist': { en: 'Waist', bn: 'কোমর' },
  'store.hip': { en: 'Hip', bn: 'নিতম্ব' },
  'store.description': { en: 'Description', bn: 'বিবরণ' },
  'store.details': { en: 'Details', bn: 'বিস্তারিত' },
  'store.reviews': { en: 'Reviews', bn: 'রিভিউ' },
  'store.selected': { en: 'selected', bn: 'নির্বাচিত' },
  'store.qty': { en: 'Qty', bn: 'পরিমাণ' },
  'store.type': { en: 'Type', bn: 'ধরন' },
  'store.items': { en: 'items', bn: 'আইটেম' },
  'store.total': { en: 'Total', bn: 'মোট' },
  'store.off': { en: 'OFF', bn: 'ছাড়' },
  'store.inStockCount': { en: 'in stock', bn: 'স্টকে আছে' },

  // ════════════ CHECKOUT EXTRA ════════════
  'store.checkout': { en: 'Checkout', bn: 'চেকআউট' },
  'store.contactInformation': { en: 'Contact Information', bn: 'যোগাযোগ তথ্য' },
  'store.emailAddress': { en: 'Email Address', bn: 'ইমেইল ঠিকানা' },
  'store.createAccountCheckout': { en: 'Create an account for faster checkout next time', bn: 'পরবর্তী সময়ে দ্রুত চেকআউটের জন্য একটি অ্যাকাউন্ট তৈরি করুন' },
  'store.address': { en: 'Address', bn: 'ঠিকানা' },
  'store.houseStreetArea': { en: 'House/Flat No, Street, Area', bn: 'বাড়ি/ফ্ল্যাট নম্বর, রাস্তা, এলাকা' },
  'store.phoneFormat': { en: 'Format: +880 1XXX-XXXXXX or 01XXX-XXXXXX', bn: 'ফরম্যাট: +৮৮০ ১XXX-XXXXXX অথবা ০১XXX-XXXXXX' },
  'store.paymentMethod': { en: 'Payment Method', bn: 'পেমেন্ট পদ্ধতি' },
  'store.giftOptions': { en: 'Gift Options', bn: 'গিফট অপশন' },
  'store.thisOrderIsGift': { en: 'This order is a gift', bn: 'এই অর্ডারটি উপহার' },
  'store.giftMessageOptional': { en: 'Gift Message (Optional)', bn: 'গিফট মেসেজ (ঐচ্ছিক)' },
  'store.giftMessagePlaceholder': { en: 'Write a personal message for the recipient...', bn: 'প্রাপকের জন্য একটি ব্যক্তিগত বার্তা লিখুন...' },
  'store.hidePricing': { en: 'Hide pricing from the package', bn: 'প্যাকেজ থেকে মূল্য লুকান' },
  'store.reviewYourOrder': { en: 'Review Your Order', bn: 'আপনার অর্ডার রিভিউ করুন' },
  'store.shippingTo': { en: 'Shipping To', bn: 'শিপিং ঠিকানা' },
  'store.payment': { en: 'Payment', bn: 'পেমেন্ট' },
  'store.goBack': { en: 'Go Back', bn: 'ফিরে যান' },
  'store.confirmAndPay': { en: 'Confirm & Pay', bn: 'নিশ্চিত করুন ও পে করুন' },
  'store.orderSummary': { en: 'Order Summary', bn: 'অর্ডার সারাংশ' },
  'store.couponCode': { en: 'Coupon code', bn: 'কুপন কোড' },
  'store.apply': { en: 'Apply', bn: 'প্রয়োগ করুন' },
  'store.free': { en: 'Free', bn: 'ফ্রি' },
  'store.days': { en: 'days', bn: 'দিন' },
  'store.freeAbove': { en: 'free', bn: 'ফ্রি' },
  'store.saveBillingAddress': { en: 'Save this billing address', bn: 'এই বিলিং ঠিকানা সংরক্ষণ করুন' },
  'store.loginForSaved': { en: 'Log in to use saved billing addresses.', bn: 'সেভ করা বিলিং ঠিকানা ব্যবহার করতে লগইন করুন।' },
  'store.chequePayment': { en: 'Cheque Payment', bn: 'চেক পেমেন্ট' },
  'store.chequeProcessed': { en: 'Your order will be processed after cheque clearance', bn: 'চেক ক্লিয়ারেন্সের পর আপনার অর্ডার প্রসেস হবে' },
  'store.instructions': { en: 'Instructions', bn: 'নির্দেশনা' },
  'store.chequeNumber': { en: 'Cheque Number', bn: 'চেক নম্বর' },
  'store.payWith': { en: 'Pay with', bn: 'পে করুন' },
  'store.secureRedirect': { en: 'You will be securely redirected to', bn: 'আপনাকে নিরাপদে রিডাইরেক্ট করা হবে' },
  'store.paymentEncrypted': { en: 'Your payment information is encrypted and secure', bn: 'আপনার পেমেন্ট তথ্য এনক্রিপ্টেড ও নিরাপদ' },
  'store.additionalCodCharge': { en: 'Additional COD charge', bn: 'অতিরিক্ত COD চার্জ' },
  'store.notifyPaymentVerified': { en: 'We will notify you once your payment is verified.', bn: 'পেমেন্ট যাচাই হলে আপনাকে জানানো হবে।' },
  'store.sentTo': { en: 'Sent to', bn: 'পাঠানো হয়েছে' },
  'store.account': { en: 'Account', bn: 'অ্যাকাউন্ট' },

  // ════════════ STORE PRODUCTS FILTER EXTRA ════════════
  'store.filters': { en: 'Filters', bn: 'ফিল্টার' },
  'store.noProductsFound': { en: 'No products found', bn: 'কোনো পণ্য পাওয়া যায়নি' },
  'store.adjustFilters': { en: 'Try adjusting your filters or search terms', bn: 'ফিল্টার বা সার্চ পরিবর্তন করে দেখুন' },
  'store.clearFilters': { en: 'Clear Filters', bn: 'ফিল্টার মুছুন' },
  'store.sortBy': { en: 'Sort by', bn: 'সাজান' },
  'store.newest': { en: 'Newest', bn: 'নতুন' },
  'store.priceLowHigh': { en: 'Price: Low to High', bn: 'মূল্য: কম থেকে বেশি' },
  'store.priceHighLow': { en: 'Price: High to Low', bn: 'মূল্য: বেশি থেকে কম' },
  'store.nameAZ': { en: 'Name A-Z', bn: 'নাম A-Z' },
  'store.priceRange': { en: 'Price Range', bn: 'মূল্য সীমা' },
  'store.rating': { en: 'Rating', bn: 'রেটিং' },
  'store.tags': { en: 'Tags', bn: 'ট্যাগ' },
  'store.onSale': { en: 'On Sale', bn: 'সেলে আছে' },
  'store.noProductsAvailable': { en: 'No products available yet.', bn: 'এখনো কোনো পণ্য পাওয়া যায়নি।' },
  'store.browseAll': { en: 'Browse All Products', bn: 'সব পণ্য দেখুন' },

  // ════════════ STORE HOME EXTRA ════════════
  'store.shopByCategory': { en: 'Shop by Category', bn: 'ক্যাটাগরি অনুযায়ী কিনুন' },
  'store.bestSellers': { en: 'Best Sellers', bn: 'সেরা বিক্রিত' },
  'store.flashSale': { en: 'Flash Sale', bn: 'ফ্ল্যাশ সেল' },
  'store.stayInLoop': { en: 'Stay in the Loop', bn: 'আপডেটেড থাকুন' },
  'store.newsletterSubtitle': { en: 'Subscribe to our newsletter for exclusive deals and new arrivals.', bn: 'এক্সক্লুসিভ ডিল ও নতুন পণ্যের জন্য আমাদের নিউজলেটারে সাবস্ক্রাইব করুন।' },
  'store.enterYourEmail': { en: 'Enter your email', bn: 'আপনার ইমেইল দিন' },
  'store.subscribe': { en: 'Subscribe', bn: 'সাবস্ক্রাইব' },

  // ════════════ ACCOUNT NOTIFICATIONS ════════════
  'account.markAllRead': { en: 'Mark all as read', bn: 'সব পঠিত হিসেবে চিহ্নিত করুন' },
  'account.noNotifications': { en: 'No notifications yet', bn: 'এখনো কোনো নোটিফিকেশন নেই' },

  // ════════════ ACCOUNT WISHLIST ════════════
  'account.myWishlist': { en: 'My Wishlist', bn: 'আমার উইশলিস্ট' },
  'account.wishlistDesc': { en: 'Products you\'ve saved for later', bn: 'পরে কেনার জন্য সংরক্ষিত পণ্য' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    return translation[language];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
